### ISSUE TITLE
Minor bugs accessing some struct variables

### ISSUE THREAD

**Issue by a3r1als** [nasa/SBN#2]
Hey, just started up a project here at work and was looking at the cFE to possibly use as the core micro-process/app interface and found a couple bugs when trying to follow the provided documentation over at nasa/cfe github. 

Attached is the patch file I generated (as a .txt since git doesn't accept .patch) 
[sbn_9aab44e .txt](https://github.com/nasa/SBN/files/1791526/sbn_9aab44e.txt)

**Comment by the-other-james** [comment]
Hi aer1als, this is an old version of SBN. A new version should be released soon... you may want to check out the development branch until then.

**Comment by a3r1als** [comment]
Got it, thanks for the info.
