### ISSUE TITLE
SBN app compatibility with cFS

### ISSUE THREAD

**Issue by SweeWarman** [nasa/SBN#22]
@CDKnightNASA Are there any test applications that I could run to verify SBN is working as expected with the latest updates to cFS? cFS nodes running SBN are no longer talking to each other after incorporating the newest changes to cFS and SBN. I keep getting the following warnings:
```
CFE_SB_42: Invalid Cmd, Unexpected Command Code 9
CFE_SB_42: Invalid Cmd, Unexpected Command Code 11
```

I am used to seeing "CPU1 connected" when two nodes start communicating with each other. That doesn't seem to happen any more.

**Comment by skliper** [comment]
SBN likely needs the MID updates for the app-to-app commands.

**Comment by CDKnightNASA** [comment]
Note that there is a test application "sbnhk" under the test folder.

I'll start looking into this issue today.

**Comment by CDKnightNASA** [comment]
ref https://github.com/nasa/cFE/issues/523
