### ISSUE TITLE
"message header + payload filter" architecture

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/SBN#24]
The logic for handling message header and body manipulation (particularly byte order and packing correction, but also mapping between header formats and other manipulation) should be modularized so that missions can develop their mission-specific remapping without having to alter the core SBN code.

Need to also consider whether this may also be incorporated into the filter/remap logic currently in SBN.

**Comment by skliper** [comment]
Also could be handled by missions customizing header access functions to handle whatever formats they expect vs manipulation of the original packet.

**Comment by jphickey** [comment]
I've been advocating for this for about 6 years now... sounds like EDS.

CFE framework really shouldn't be picking/choosing to "fix" or be format-aware of certain fields and not others, we will be chasing this forever.  The only real solution is to have a mission DB that has all the details of all packets in it so the content can be properly byteswapped and padded/unpadded per system requirements across the board without having to write explicit code for each individual field.

EDS does that, but so do potentially other solutions too, just need to settle on one and integrate it.
