### ISSUE TITLE
Comparison with nng, nanomsg and ZeroMQ?

### ISSUE THREAD

**Issue by ChristopherRabotin** [nasa/SBN#3]
I'm curious to see how the SBN compares with [nng](https://github.com/nanomsg/nng) and other such data buses.

Moreover, has the SBN been flight proven yet?

I'm posting here because the [cFS](http://coreflightsystem.org/questions/question/) forums are down (500 internal error).

Thanks.

**Comment by CDKnightNASA** [comment]
SBN is an app that bridges cFS software buses (SB's) and is network transport agnostic--there is a core application that connects to the SB and links in one or more network transport modules and uses those modules to transmit and receive messages from peers in the SBN network. SBN efficiently utilizes networks by only sending messages to peers that have subscriptions for those message ID's. SBN handles the automatic exchange of this subscription information between peers.

It would be straightforward to develop a protocol module for SBN to have it utilize nng or ZeroMQ or any other network protocol layer.
